---
- name: Instalar OpenJDK 11 JRE (headless) en Ubuntu 22.04
  hosts: central
  become: true

  tasks:
    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar OpenJDK 11 JRE (headless)
      apt:
        name: openjdk-11-jre-headless
        state: absent 
